server:
  port: 8082

spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000 #5 seconds
          max-attempts: 3
          max-interval: 5000 #5 seconds
          multiplier: 1

play-music:
  exchange: play-music-topic-ex
  exchange-error: play-music-pop-dlx

  queues: pop-song-international
  queues-error: pop-song-international-dlq
  routing-keys: pop.international