server:
  port: 8081

spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000 #5 seconds
          max-attempts: 3
          max-interval: 5000 #5 seconds
          multiplier: 1

play-music:
  exchange: play-music-topic-ex
  exchange-error: play-music-rock-dlx

  queues: rock-song
  queues-error: rock-song-dlq
  routing-keys: rock.*