server:
  port: 8081

spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
          multiplier: 2
          max-interval: 300000

    connection:
      host: localhost
      port: 5672
      username: guest
      password: guest

play-music:
  exchange: play-music-topic-ex
  exchange-error: play-music-rock-dlx

  queues: rock-song
  queues-error: rock-song-dlq
  routing-keys: rock.*