server:
  port: 8080

rabbitmq:
  connection:
    host: localhost
    port: 5672
    username: guest
    password: guest

play-music:
  exchange: play-music-topic-ex

#Way to create all the queues just one producer
#queues:
#  play-music:
#    queues: rock-song,pop-song-international
#    routing-keys: rock.*,pop.international
#    exchange: play-music-topic
#    exchange-error: play-music-topic-dead-letter