server:
  port: 8080

rabbitmq:
  connection:
    host: localhost
    port: 5672
    username: guest
    password: guest

queues:
  play-music:
    queues: rock-song,pop-song-international
    routing-keys: rock.*,pop.international
    exchange: play-music-topic
    exchange-error: play-music-topic-dead-letter